# User config
author: ""
tagline: "B"
description: ""
keywords: ""
email: ""
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/home"
highlighter: rouge
